joint_limits:
  ur3_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 3.5
    has_jerk_limits: false
    max_jerk: 0.0
  ur3_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 3.5
    has_jerk_limits: false
    max_jerk: 0.0
  ur3_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 3.5
    has_jerk_limits: false
    max_jerk: 0.0
  ur3_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 3.5
    has_jerk_limits: false
    max_jerk: 0.0
  ur3_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 3.5
    has_jerk_limits: false
    max_jerk: 0.0
  ur3_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: true
    max_acceleration: 3.5
    has_jerk_limits: false
    max_jerk: 0.0
  robotiq_hande_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.15
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 0.0