# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - gripper

  gripper:
    type: GripperCommand
    joints:
      []
    action_ns: gripper_cmd
    default: true